# Generated by Django 5.2.1 on 2026-05-10 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='category',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='id_image',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='id_with_image',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='licence_image',
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
